# Generated by Django 4.1.5 on 2023-02-04 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Session_Year',
            new_name='SessionYear',
        ),
    ]
