# Generated by Django 4.1.5 on 2023-02-20 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0009_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages', models.CharField(max_length=200)),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.staff')),
            ],
        ),
    ]
