# Generated by Django 4.1.5 on 2023-02-20 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0011_staffnotification_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffnotification',
            name='status',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
