# Generated by Django 4.1.5 on 2023-02-22 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0014_alter_student_session_year_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_apply_date', models.CharField(max_length=50)),
                ('leave_from', models.CharField(max_length=50)),
                ('leave_to', models.CharField(max_length=50)),
                ('subject', models.TextField()),
                ('message', models.TextField()),
                ('status', models.IntegerField(default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.staff')),
            ],
        ),
    ]
