# Generated by Django 4.1.6 on 2023-02-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0015_leaverequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='subject',
            field=models.CharField(max_length=200),
        ),
    ]
