# Generated by Django 4.1.7 on 2023-02-23 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0017_staff_feedback'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Staff_Feedback',
            new_name='StaffFeedback',
        ),
    ]
